version: "3.9"
services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_PASSWORD=P35Bxzz6K
      - POSTGRES_DB=simple_bank
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgresql://postgres:P35Bxzz6K@postgres:5432/simple_bank?sslmode=disable
    